#!/bin/sh
SCALA_BISON_HOME=`dirname $0`/..
# bison MUST be version 1.875 or later
bison -v $1.y
rm $1.tab.c
scala -cp $SCALA_BISON_HOME/scala-bison.jar -howtorun:object edu.uwm.cs.scalabison.RunGenerator -v $1.y
rm $1.output
